name: build-test

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6
          run_install: true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm test-ci
      - run: pnpm build
